url:          'http://hal.computer'
remote_theme: 'qwtel/hydejack'

title:        'Hal Deployment Platform'
logo:         '/favicon.ico'
description:  >
    Hal is a web-based deployment platform built with PHP.

author:
    github: 'hal-platform'

google_fonts: 'Russo+One|Noto+Sans'
font:         '"Noto Sans", Helvetica, Arial, sans-serif'
font_heading: '"Russo One", Helvetica, Arial, sans-serif'

accent_image: 'xxx.png'
accent_color: '#d84930'
