url:          'http://hal.computer'
remote_theme: 'qwtel/hydejack'

title:        'Hal Deployment Platform'
logo:         '/favicon.ico'
description:  >
    Hal is a web-based deployment platform built with PHP.

google_fonts: 'Russo One'
font:         '"Russo One", sans-serif;'

accent_image: ''
accent_color: '#d84930'
